1 int _putchar(char c);
2 void print_alphabet(void);
3 void print_alphabet_x10(void);
4 int _islower(int c);
5 int _isalpha(int c);
6 int print_sign(int n);
7 int _abs(int);
8 int print_last_digit(int);
9 void jack_bauer(void);
10 void times_table(void);
11 int add(int, int);
12 void print_to_98(int n);
